"""
One-shot reproducibility script for `data_processed/agentic_intent_synthesized.csv`.

Per CONTEXT D-05 / D-06 / D-07 and RESEARCH Assumption A3, the LLM expansion of the
30 hand-written agentic seeds into ~450 paraphrastic variations is a ONE-TIME OFFLINE
step performed by the developer using their own LLM. The synthesized rows are embedded
verbatim in this file so that re-running the script reproduces the exact same CSV
(no nondeterminism from a live LLM call), and so that the dataset's provenance is
diff-able in the repo.

Authored by: Claude Opus 4.7 (via Claude Code), 2026-05-13.
Source seeds: data_processed/agentic_intent_seeds.csv (30 rows).
Target: ~450 rows, balanced across the seed list, varying along
  - verb diversity (build/make/create/spin up/cook up; write/author/draft/code up; etc.)
  - prompt length (5-200 tokens; ~3 very-short, ~4 short, ~5 medium, ~3 long per seed)
  - phrasing style (imperative, polite, declarative, telegram)
  - domain spread (finance -> fitness, AWS -> GCP/Azure, etc.)
Schema: text,label,source,dataset with label=agentic, source=synthesized, dataset=llm-expansion.

Run:
    uv run python scripts/expand_agentic_seeds.py
"""
from __future__ import annotations

import csv
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "data_processed" / "agentic_intent_synthesized.csv"

SEED_VARIATIONS: dict[str, list[str]] = {
    # ---- Seed 1: finance dashboard ----
    "build me a small finance dashboard that tracks my monthly spending": [
        "make a budget dashboard",
        "spending tracker UI please",
        "build a personal finance dashboard for me",
        "Build a small dashboard that visualizes my monthly expenses by category.",
        "Could you put together a personal finance dashboard so I can track what I spend each month?",
        "Create a fitness dashboard that logs my weekly workouts and calorie intake.",
        "Use Streamlit to build a dashboard showing my credit card spending broken out by month.",
        "Build a small finance dashboard, mobile-friendly, no auth required, deployable to Fly.io.",
        "I have a CSV export from my bank with daily transactions. Build me a dashboard that aggregates them by month and category and shows the trend over the last 6 months. Plotly or Streamlit, your call.",
        "Spin up a finance dashboard using Next.js on the frontend and FastAPI on the backend; ingest bank CSVs, store transactions in SQLite, and render monthly spending broken down by merchant category.",
        "I'd really appreciate it if you could put together a small personal finance dashboard. It needs to track my monthly spending across groceries, rent, subscriptions, and eating out, and ideally show me how my spending has evolved over the last year.",
        "Build a finance dashboard. Inputs: monthly bank statements as CSVs in ~/Documents/finance/. Outputs: an HTML report showing category breakdown, month-over-month delta, and a savings-rate calculation. Use whatever Python charting library you prefer.",
        "Build me a small travel-spending dashboard that tracks my trip expenses by country and category.",
        "Make a dashboard that tracks all my recurring subscriptions and flags any I haven't used in 60 days.",
        "Create a dashboard that tracks revenue from my Etsy shop by product and month.",
    ],
    # ---- Seed 2: AWS bill CLI ----
    "write a CLI tool that summarizes my AWS bill by service and region": [
        "AWS cost CLI please",
        "cli to summarize cloud spend",
        "draft a CLI that breaks down my AWS bill",
        "Write a small CLI tool that summarizes my AWS bill by service and region.",
        "Author a Python CLI that pulls cost-explorer data and prints a per-service breakdown.",
        "Could you put together a command-line tool that summarizes my GCP bill by project and SKU?",
        "Build a CLI named `awscost` that uses boto3 and prints a markdown table of last month's spend.",
        "Write a Go binary that reads cost-explorer JSON and prints the top 10 services by monthly cost.",
        "I need a CLI that summarizes my Azure subscription bill by resource group and region, output as JSON for further processing.",
        "Write a CLI tool that reads my AWS cost-explorer data via boto3, aggregates spend by service and region, prints a sorted table to stdout, and optionally writes CSV with `--out`. Should handle multi-account orgs.",
        "Cook up a CLI that summarizes my Stripe billing data — fees, payouts, refunds — broken down by month and product.",
        "Could you write me a command-line tool that pulls the last 90 days of AWS cost-explorer data, groups it by service, region, and tag, and prints a colorized table? Bonus points if it has a `--diff` flag to compare against the previous period.",
        "make a cli `gcloud-summary` that breaks down gcp spend",
        "Write a Python script with argparse that ingests an AWS Cost and Usage Report CSV and prints aggregate spend by service.",
        "Build a CLI that summarizes my Cloudflare Workers usage and cost broken down by zone and request type.",
    ],
    # ---- Seed 3: scrape HN headlines ----
    "create a Python script that scrapes Hacker News front-page headlines into a CSV": [
        "scrape HN front page to csv",
        "python script: pull HN headlines",
        "write a scraper for Hacker News headlines",
        "Create a Python script that scrapes the HN front page and saves headlines to a CSV.",
        "Author a small scraper that pulls the top 30 Hacker News stories into a CSV with title, score, comments, url.",
        "Could you write a Python script that scrapes Lobsters front-page stories into a CSV?",
        "Build a scraper that pulls Reddit r/programming top posts of the day into JSON.",
        "Write a Python script that uses requests+BeautifulSoup to scrape news.ycombinator.com and save headlines, points, and submitter into a SQLite database.",
        "I need a scraper that pulls the front page of Hacker News every hour and appends new stories to a CSV without duplicates. Idempotent on rerun.",
        "Write a Python script that scrapes Product Hunt's homepage daily and saves the top launches into a CSV with name, tagline, upvotes, and launch date.",
        "create a python script that grabs the top 50 Hacker News stories with full metadata (title, url, points, comments, age) and writes them to a CSV named hn_$(date).csv",
        "Could you put together a small scraper that uses the Hacker News Firebase API to fetch the top 100 stories and saves them to CSV? No HTML parsing if there's a JSON endpoint.",
        "Write a Python script that scrapes the latest 100 stories from Hacker News, filters to those tagged 'show hn', and writes them to a CSV.",
        "Build a scraper that pulls headlines from the top 5 tech newsletters' RSS feeds and consolidates them into a single CSV.",
        "draft a python web scraper for news.ycombinator.com saving title+url+score to csv",
    ],
    # ---- Seed 4: Flask -> FastAPI refactor ----
    "refactor my Flask app to use FastAPI and async endpoints": [
        "flask -> fastapi",
        "migrate flask routes to fastapi async",
        "convert my Flask backend to FastAPI",
        "Refactor my Flask application to use FastAPI with async endpoints.",
        "Port my Flask app to FastAPI, keeping the route paths identical so the frontend doesn't need changes.",
        "Could you migrate my Flask blueprints over to FastAPI routers, switching the handlers to async def?",
        "Refactor this Django REST Framework project to use FastAPI instead, preserving the OpenAPI spec.",
        "Migrate my Express server to Hono, converting the middleware chain and switching to async handlers.",
        "I have a Flask app with about 40 routes. Refactor it to FastAPI, convert the SQLAlchemy code to async with asyncpg, and make sure all the tests still pass.",
        "Rewrite my Flask + Celery setup using FastAPI + Arq, with async endpoints and async background tasks. Preserve all existing API contracts.",
        "Port my Sinatra app to a Rails API-only project with async controllers using fibers.",
        "rework this flask app into fastapi w/ async db calls (sqlmodel) and websocket support",
        "Could you refactor my Flask backend to FastAPI, replacing all the @app.route decorators with the equivalent FastAPI decorators and converting blocking I/O to async? The DB layer is SQLAlchemy 1.4 — keep using it but switch to the async session.",
        "Migrate my Python 3.9 Flask app to FastAPI on Python 3.12. Bring everything async, swap requests for httpx, and use Pydantic v2 models for request/response validation.",
        "Refactor my AIOHTTP service to FastAPI, preserving the WebSocket endpoints and using Starlette's WebSocket primitives.",
        "Convert my Flask + gunicorn setup to FastAPI + uvicorn with proper async endpoints throughout.",
    ],
    # ---- Seed 5: BST implementation ----
    "implement a binary search tree with insert, find, and delete operations": [
        "implement BST",
        "code up a binary search tree",
        "write a BST class in python",
        "Implement a binary search tree with insert, find, and delete operations.",
        "Write a TypeScript class for a self-balancing AVL tree with insert/find/delete.",
        "Could you implement a red-black tree in Rust with insertion, deletion, and rank queries?",
        "Code up a trie data structure in C++ with insert, search, and prefix-search operations.",
        "Implement a skip list in Go supporting O(log n) insert, search, and delete.",
        "Write a B-tree in Python that supports insert and range queries, suitable for a small on-disk index.",
        "I need a generic balanced BST in TypeScript — splay trees would be fine — with insert, find, delete, and successor/predecessor queries. Include benchmarks against the builtin Map.",
        "Implement a binary search tree from scratch in Rust. Required ops: insert, find, delete, in-order traversal, count, height. Include a derived Debug impl that prints the tree nicely, and unit tests for each operation including the three-deletion-cases.",
        "Write a treap in Haskell with insert, delete, and member operations, supporting concurrent access via STM.",
        "implement a bst class with insert/find/delete plus an iterator that yields keys in sorted order",
        "Could you put together a simple unbalanced BST in JavaScript that supports add, has, remove, and forEach in sorted order? I need it for a coding interview prep doc.",
        "Implement a segment tree with point-update and range-sum queries in C++.",
        "Code up a 2-3 tree in OCaml with insertion and lookup, following the textbook algorithm exactly.",
    ],
    # ---- Seed 6: unit tests for auth ----
    "add unit tests for the auth module covering the JWT refresh flow": [
        "add tests for jwt refresh",
        "unit tests for auth module",
        "write tests covering the refresh-token flow",
        "Add unit tests for the auth module covering the JWT refresh flow.",
        "Write pytest tests for the session-renewal logic in user/session.py.",
        "Could you add unit tests around the OAuth2 callback handler, especially the state-mismatch edge case?",
        "Write Jest tests for the auth middleware covering valid token, expired token, and missing-bearer-prefix cases.",
        "Add a unit-test suite for the password-reset flow: token issuance, token consumption, double-use detection.",
        "I need pytest tests for the JWT refresh endpoint that cover: valid refresh, expired refresh, revoked refresh, refresh from a different IP, and rate-limited refresh.",
        "Write a thorough Jest test file for our authentication module. Cover happy path (login -> access token -> refresh -> new access token), all sad paths (bad password, locked account, expired refresh, reused refresh), and verify that revoking a refresh token invalidates downstream access tokens after their TTL.",
        "Add unit tests around the magic-link auth flow in auth/magic.py: link issuance, link consumption, double-use, expired link, link from wrong email.",
        "add pytest cases for auth.refresh covering happy + 5 sad paths, mock the kv store",
        "Could you write unit tests for the session-cookie middleware? I want coverage on the Secure/HttpOnly/SameSite=Lax flags, on expired sessions, and on the case where the signing key has rotated mid-session.",
        "Write unit tests for the WebAuthn registration ceremony in auth/webauthn.py — successful registration, replay attack rejection, and attestation-format failures.",
        "Add unit tests for the SAML response handler, especially around signature validation and time-window enforcement.",
        "Write tests for the API-key auth path: valid key, revoked key, expired key, key with insufficient scope.",
    ],
    # ---- Seed 7: pagination off-by-one ----
    "fix the off-by-one bug in pagination.py that drops the last record on every page": [
        "fix pagination off-by-one",
        "patch pagination.py — last row missing",
        "debug pagination bug dropping records",
        "Fix the off-by-one bug in pagination.py that drops the last record on every page.",
        "Patch the bug in pagination.py — last item of every page is missing on the frontend.",
        "Could you fix the off-by-one in cursor-pagination.ts? It's skipping the row at the page boundary.",
        "Debug and fix the bug in api/list_orders that returns N-1 items when the limit is N.",
        "Hunt down why the orders endpoint drops the last record on every page and fix it without changing the public API.",
        "There's an off-by-one bug in pagination.py — pages have size limit-1 instead of size limit. Find the root cause and fix it; don't just paper over the symptom.",
        "Fix the pagination bug in api/v1/users — calling with limit=50 returns 49 users and the 50th appears as the first item of the next page (so it gets dropped on the frontend that uses set-based dedup).",
        "I think there's an off-by-one in the cursor-based pagination of the activity feed. The last event of each page is being dropped before it reaches the response serializer. Find the bug and fix it; add a regression test.",
        "fix the pagination bug in api/orders.py — every page is missing its last row",
        "Could you investigate why our pagination is dropping records? Reproducer: GET /api/items?limit=10&offset=0 returns 9 items, then GET /api/items?limit=10&offset=10 also drops one. Fix and add a regression test.",
        "Patch the bug in api/list.py where the `nextCursor` field is one row stale, causing the frontend to skip a record on every page transition.",
        "Fix the pagination calculation in dashboard.tsx — the `Showing X-Y of Z` label is off by one for the last page.",
        "Investigate and fix the bug in our SSR-paginated table where the last row of each page is replaced by the first row of the next page.",
    ],
    # ---- Seed 8: Dockerfile Python 3.12 slim ----
    "edit my Dockerfile to use Python 3.12 and a slim base image": [
        "update Dockerfile to py3.12-slim",
        "switch dockerfile base to python:3.12-slim",
        "bump the python version in my Dockerfile",
        "Edit my Dockerfile to use Python 3.12 and a slim base image.",
        "Update the Dockerfile to bump from python:3.10 to python:3.12-slim.",
        "Could you migrate my Dockerfile from python:3.9-alpine to python:3.12-slim?",
        "Switch my Dockerfile base from node:18 to node:20-alpine and update package-lock.json accordingly.",
        "Update my Dockerfile to multi-stage build using python:3.12-slim and reduce final image size below 200 MB.",
        "Edit the Dockerfile to use Python 3.12, a slim base, and copy only the production artifacts into the final stage; drop the build tooling from the runtime image.",
        "Rewrite the Dockerfile as a multi-stage build using python:3.12-slim, copying the uv-built virtualenv from the builder stage into the runtime stage. Final image should be under 150 MB.",
        "Update my Dockerfile so it uses python:3.12-slim, runs as a non-root user, and pre-bakes the NLTK punkt_tab corpus into the image so the runtime doesn't download it on first request.",
        "edit Dockerfile: base=python:3.12-slim, add a non-root user, healthcheck=curl localhost:8000/health, expose 8000",
        "Could you take my Dockerfile that uses python:3.9 and bring it up to Python 3.12 on a slim base? Also switch from pip to uv for the install step.",
        "Modify the Dockerfile to use python:3.12-slim-bookworm, pin all apt packages with --no-install-recommends, and use BuildKit cache mounts for the apt cache.",
        "Update my Dockerfile to Python 3.12-slim and switch from CMD to ENTRYPOINT so signals are forwarded correctly to gunicorn.",
        "Refactor the Dockerfile to support both arm64 and amd64 with buildx and a slim Python 3.12 base.",
    ],
    # ---- Seed 9: regex catastrophic backtracking ----
    "rewrite this regex to run in O(n) and not catastrophically backtrack": [
        "fix this regex's backtracking",
        "rewrite regex for O(n)",
        "patch slow regex",
        "Rewrite this regex so it runs in O(n) and doesn't catastrophically backtrack.",
        "Refactor the email-validation regex to eliminate the nested-quantifier backtracking.",
        "Could you rewrite this url-matching regex without the nested * / + that's causing ReDoS?",
        "Patch the slow regex in routes.ts — it's pinning a CPU core on certain inputs.",
        "Rewrite the regex in input-sanitizer.py to use atomic groups (or a converted character class) so it can't catastrophically backtrack.",
        "I have a regex that matches `(a+)+$` style patterns and ReDoS's on adversarial input. Rewrite it as a linear-time finite automaton, or convert to character-class form.",
        "Refactor this regex to be linear-time. Inputs longer than 5000 chars currently time out. Use possessive quantifiers if the engine supports them, otherwise unroll the alternation.",
        "Rewrite our credit-card-detection regex to eliminate the nested-quantifier ReDoS reported by Snyk last week. Maintain the same set of matched cases.",
        "rewrite this regex pattern to be backtracking-safe: ^(a+)+b$",
        "Could you fix the regex in src/parsers/log_line.rs that's choking on log lines longer than 10 KB? Pretty sure it's a catastrophic backtracking issue on the nested capture group.",
        "Rewrite the user-agent parsing regex to use a possessive-quantifier form (or pre-anchor the alternation) so it runs in linear time.",
        "Convert this email regex to RFC-5322-compliant form using a proper PEG parser instead of a single regex.",
        "Refactor the regex in middleware/validate.js so it cannot ReDoS — replace nested quantifiers with character classes or atomic groups.",
    ],
    # ---- Seed 10: sqlx schema todo list ----
    "generate a sqlx schema for a todo-list app with users, lists, and items": [
        "sqlx schema for todo app",
        "make me a todo-list db schema",
        "generate SQL for a todo app",
        "Generate a sqlx schema for a todo-list app with users, lists, and items.",
        "Write the SQL migrations for a todo app — users, lists, items, sharing, and audit logs.",
        "Could you create a Postgres schema for a recipe app: users, recipes, ingredients, steps, and tags?",
        "Generate a Drizzle ORM schema for a kanban board with workspaces, boards, columns, and cards.",
        "Author Diesel migrations for a tiny CRM: contacts, organizations, deals, and notes.",
        "Generate a sqlx-compatible Postgres schema for a multi-user todo app. Tables: users (with email+hashed password), lists (per user, soft-delete capable), items (with priority and due date), and a many-to-many for shared lists. Include indexes and FK constraints.",
        "Create a full database schema for a small task-tracking app. Users, lists, items, comments, attachments, tags, and a many-to-many tag_items table. Add appropriate indexes for the common queries (items by list, items by tag, comments by item), foreign keys, and check constraints.",
        "Write the SQLx migration files for a todo app supporting offline-first sync via CRDTs — give every mutable column a Lamport-timestamp companion column.",
        "draft postgres ddl for a todo app: users, lists, items, with proper fk + index",
        "Could you generate the migration files for a todo-list MVP? Postgres, sqlx-rust. Three tables — users, lists, items — with the obvious foreign keys. Include `created_at` and `updated_at` everywhere.",
        "Write the Prisma schema for a todo-list app and include the necessary `@@unique` and `@@index` directives for production performance.",
        "Generate a SQLite schema (suitable for use via sqlx) for a personal todo app with users, lists, items, and a recurring-task table.",
        "Author the DDL for a todo-list backend in MySQL 8, including indexes for the common access patterns.",
    ],
    # ---- Seed 11: HN summarize ----
    "open https://news.ycombinator.com and summarize the top 5 stories for me": [
        "summarize HN top 5",
        "open HN and tell me top stories",
        "browse Hacker News and give me a summary",
        "Open https://news.ycombinator.com and summarize the top 5 stories for me.",
        "Visit Hacker News and give me a one-paragraph summary of the top 10 stories.",
        "Could you open Lobsters and summarize the top 5 stories I haven't seen?",
        "Browse to news.ycombinator.com and tell me which of the top 30 are about AI safety.",
        "Open r/programming and summarize the top 5 posts of today.",
        "Open Hacker News, click into each of the top 5 stories, and give me a one-sentence summary of each story plus a one-sentence summary of the top comment.",
        "Visit https://news.ycombinator.com, look at the top 30 stories, filter to ones with more than 200 points, click each, and produce a structured digest with title, link, points, summary, and the most insightful comment for each.",
        "Open lobste.rs and Hacker News in parallel and produce a combined top-10 digest, de-duped by URL.",
        "go to https://news.ycombinator.com and summarize the top 5 with title + key takeaway each",
        "Could you visit the Hacker News front page and produce a quick digest of the top 5 stories? Just title + a one-sentence summary of what each story is about.",
        "Open https://news.ycombinator.com/show and summarize the top 5 Show HN submissions of the week.",
        "Browse to the Hacker News best-of-the-day page and produce a digest of the top 10 with takeaways.",
        "Visit lwn.net and summarize the top 5 stories on the front page.",
    ],
    # ---- Seed 12: amazon usb-c charger ----
    "navigate to amazon.com and find a USB-C charger under $20 with prime shipping": [
        "find me a usb-c charger under $20",
        "amazon: usb-c charger <$20 + prime",
        "shop amazon for a cheap usb-c charger",
        "Navigate to amazon.com and find a USB-C charger under $20 with prime shipping.",
        "Go to amazon.com and find me the highest-rated USB-C wall charger under $20 with Prime.",
        "Could you browse amazon.com and find a 65W GaN charger under $40 with two-day shipping?",
        "Open amazon and find me a USB-C to Lightning cable that's MFi certified, under $15, Prime-eligible.",
        "Visit walmart.com and find me a 1TB SSD under $80 with free shipping.",
        "Navigate to amazon.com, search for USB-C chargers, filter to under $20 with Prime, and give me the top 3 by review count along with their prices and ratings.",
        "Browse amazon.com and find me a 4-port USB-C wall charger that is at least 65W total, under $30, has Prime two-day shipping, and at least 4.5 stars with 500+ reviews. Give me the top 3 candidates with prices and the deciding-factor differences.",
        "Open Best Buy and find a 27\" 4K monitor under $300 that ships free this week.",
        "find cheapest usb-c charger on amazon w/ prime + 4+ stars",
        "Could you go to amazon.com and find me a USB-C charger? Constraints: under $20, Prime shipping, 30W or higher, at least 4 stars, currently in stock. Give me the top 3 with quick pros/cons.",
        "Navigate to Newegg and find a 1TB NVMe SSD under $70 with free shipping.",
        "Visit https://amazon.com and find a 100W USB-C GaN charger under $40, Prime-eligible.",
        "Open ebay and find me a used USB-C charging dock for the iPad Pro under $30.",
    ],
    # ---- Seed 13: newsletter subscribe ----
    "click the subscribe button on this newsletter page and confirm the opt-in email": [
        "subscribe me to this newsletter",
        "click subscribe + confirm email",
        "complete this newsletter signup flow",
        "Click the subscribe button on this newsletter page and confirm the opt-in email.",
        "Subscribe me to this Substack and click the confirmation link in my inbox.",
        "Could you click the 'Get notified' button on this product page and confirm the email when it arrives?",
        "Sign me up for this mailing list and confirm the double-opt-in confirmation.",
        "Open this newsletter signup page, click subscribe, then check Gmail for the confirmation email and click the verify link.",
        "Visit https://platformer.news, click the subscribe link, fill in my email address, and confirm the double-opt-in email that lands in my inbox.",
        "Go to https://stratechery.com, click the 'Subscribe' button, enter my standard email, complete the Stripe checkout for the annual subscription, then open the welcome email and click the verify link.",
        "Click the 'Join the waitlist' button on this product page and verify the confirmation email.",
        "subscribe + verify the opt-in email for this newsletter page",
        "Could you go to the Pragmatic Engineer signup page, click subscribe with my work email, and then click the confirmation link they send? My email client is already open in another tab.",
        "Open this RSS-aggregator landing page, click 'Get early access', fill in my email, and confirm.",
        "Click the 'Notify me' button on this restaurant's reservation page and confirm the SMS opt-in.",
        "Sign me up for the OpenAI changelog newsletter and click the verification email.",
    ],
    # ---- Seed 14: contact form ----
    "fill out the contact form at https://example.com/contact with my standard intro": [
        "fill the contact form for me",
        "submit my intro on example.com/contact",
        "complete this contact form",
        "Fill out the contact form at https://example.com/contact with my standard intro.",
        "Go to example.com/contact and submit the form using my standard pitch text.",
        "Could you fill out the inquiry form on https://acme.io/contact-sales with my elevator pitch?",
        "Open this Calendly page, pick a 30-min slot next Tuesday afternoon, and book it under my name.",
        "Submit the partnership-inquiry form at https://stripe.com/contact with my company info and pitch.",
        "Fill out the contact form at https://example.com/contact: name, email, phone, message field gets my standard intro paragraph. Confirm submission.",
        "Visit https://example.com/contact and complete the contact form with my standard introduction. Subject line: 'API integration question'. Attach my company one-pager from ~/Documents/onepager.pdf. Submit and screenshot the confirmation page.",
        "Open https://stripe.com/contact, fill out the sales-inquiry form for a Series-B fintech use case using my company details, and submit.",
        "fill out https://example.com/contact w/ my standard intro and hit send",
        "Could you visit https://example.com/contact and fill out the form with my standard intro and submit? Use my work email and select 'Sales inquiry' as the category.",
        "Open https://shopify.com/plus/contact-sales and submit my company's interest in their enterprise plan using my standard intro.",
        "Visit https://intercom.com/contact and fill out the demo-request form with my standard intro.",
        "Submit the contact form on https://typeform.com/contact for a sales inquiry, using my standard intro.",
    ],
    # ---- Seed 15: resume submission ----
    "submit my resume PDF to the careers page at https://acme.io/jobs/staff-engineer": [
        "submit my resume to acme",
        "apply for the staff engineer role",
        "send my resume to acme careers",
        "Submit my resume PDF to the careers page at https://acme.io/jobs/staff-engineer.",
        "Apply to the staff engineer role at https://acme.io/jobs/staff-engineer using my resume PDF from Downloads.",
        "Could you submit my application to https://stripe.com/jobs/listing/staff-backend-engineer/12345?",
        "Apply to this senior SRE position with my resume and a tailored cover letter.",
        "Open https://acme.io/jobs/staff-engineer, attach ~/Documents/resume.pdf, fill in name/email/LinkedIn, and submit.",
        "Visit the careers page at https://acme.io/jobs/staff-engineer, upload my resume.pdf from ~/Downloads, complete all required fields with my standard info, and submit. Take a screenshot of the confirmation.",
        "Apply to the Staff Backend Engineer role at Stripe (https://stripe.com/jobs/listing/staff-backend-engineer). Use my resume from ~/Documents, generate a one-page cover letter tailored to the role's emphasis on payments infrastructure, and submit the application.",
        "Submit my resume to the Workday-hosted careers portal at https://acme.wd5.myworkdayjobs.com/ext/jobs/staff-eng.",
        "apply to acme.io/jobs/staff-engineer w/ my resume.pdf — submit + screenshot confirmation",
        "Could you go to https://acme.io/jobs/staff-engineer, upload my resume from ~/Documents/resume.pdf, fill in the standard fields (name, email, phone, LinkedIn), tick 'Yes' on the work-authorization question, and submit? Then send me the application ID.",
        "Apply to the Principal Engineer role at https://datadog.com/careers/principal-eng using my resume and standard cover letter.",
        "Submit my CV to https://gitlab.com/jobs/staff-engineer-fullstack, including the diversity-survey responses set to 'prefer not to say'.",
        "Apply to the staff-level role on https://lattice.com/careers/staff-engineer with my resume and standard intro.",
    ],
    # ---- Seed 16: gmail unread count ----
    "browse to my Gmail inbox and report the count of unread messages from last week": [
        "how many unread emails last week?",
        "check my gmail for unread count",
        "tell me my unread email count",
        "Browse to my Gmail inbox and report the count of unread messages from last week.",
        "Open Gmail and tell me how many unread emails I have from the past 7 days.",
        "Could you check my Outlook inbox and count messages from this week tagged 'work'?",
        "Open Gmail, filter to unread + last 7 days, and report the count broken down by sender domain.",
        "Visit my Fastmail inbox and report how many unread newsletters I have waiting.",
        "Open Gmail, navigate to my inbox, count the unread emails from the past 7 days, and break the count down by label (Work, Personal, Newsletters).",
        "Go to Gmail, search for `is:unread newer_than:7d` in my inbox, count the results, break them down by sender, identify which 5 senders contributed the most unread mail, and write me a one-paragraph summary recommending which ones I should consider unsubscribing from.",
        "Open my Proton Mail inbox and count unread messages tagged 'urgent' from the past 14 days.",
        "browse to gmail inbox and tell me unread count for last 7 days",
        "Could you log in to my Gmail (I'm already authed in the browser session), open the inbox, filter to `is:unread newer_than:7d`, and report the count plus the top 5 senders?",
        "Open Hey email and count my Imbox arrivals from this week that I haven't read yet.",
        "Visit my Gmail and count unread emails from work senders (domain ends with @mycompany.com) over the past week.",
        "Open Gmail and report the count of unread emails older than 30 days that I should consider archiving.",
    ],
    # ---- Seed 17: github star count ----
    "visit https://github.com/microsoft/vscode and tell me the current star count": [
        "vscode star count?",
        "check github stars for microsoft/vscode",
        "how many stars does vscode have",
        "Visit https://github.com/microsoft/vscode and tell me the current star count.",
        "Open the microsoft/vscode repo on GitHub and report its star count.",
        "Could you check https://github.com/rust-lang/rust and tell me the star count and most recent release tag?",
        "Open https://github.com/openai/openai-python and tell me how many open issues there are right now.",
        "Visit https://github.com/withastro/astro and report stars, forks, and open PRs.",
        "Open https://github.com/microsoft/vscode and report stars, forks, open issues, open PRs, and the most recent release tag.",
        "Visit https://github.com/microsoft/vscode, capture stars / forks / open PRs / open issues, then compare to the cached numbers from 30 days ago in my notes and tell me the delta.",
        "Check https://github.com/nodejs/node for the star count and open security advisories.",
        "browse to github.com/microsoft/vscode and tell me current stars + last release tag",
        "Could you visit https://github.com/microsoft/vscode and tell me how many stars it has? Bonus: also tell me how many it had a year ago (try the Wayback Machine).",
        "Open https://github.com/anthropics/anthropic-sdk-python and report stars, forks, and the latest tag.",
        "Visit https://github.com/torvalds/linux and report the star count and number of contributors.",
        "Browse to the python/cpython repo on GitHub and tell me current stars + how many open issues are labeled 'easy'.",
    ],
    # ---- Seed 18: stripe invoice download ----
    "download the latest invoice from https://stripe.com and save it to my Downloads": [
        "grab my latest stripe invoice",
        "download my stripe invoice to ~/Downloads",
        "save the most recent stripe invoice",
        "Download the latest invoice from https://stripe.com and save it to my Downloads.",
        "Open my Stripe dashboard, find the latest invoice, and download it as PDF to ~/Downloads.",
        "Could you grab the most recent invoice from my Paddle dashboard and save it locally?",
        "Open my AWS Billing console and download last month's invoice as PDF.",
        "Visit my Vercel dashboard, download the last 3 monthly invoices, and save them to ~/Documents/invoices/.",
        "Log into my Stripe dashboard, navigate to the invoices section, download the most recent invoice as a PDF, and save it to ~/Downloads with the filename `stripe_{YYYY-MM}.pdf`.",
        "Open my Stripe billing portal, list all invoices from the last quarter, download each as PDF into ~/Documents/invoices/2026-Q1/, and write me a summary CSV with invoice_id, amount, date, and product.",
        "Download every invoice from my Linear billing page and save them in ~/Documents/invoices/linear/.",
        "save my latest stripe invoice to ~/Downloads",
        "Could you go to https://stripe.com (I'm logged in), open the billing dashboard, find the most recent invoice (should be dated this month), and download it as PDF to my ~/Downloads folder? Rename it to `stripe-$(date +%Y%m).pdf` after download.",
        "Open my GitHub billing settings and download the latest receipt for my Pro subscription.",
        "Visit my Cloudflare dashboard and download the most recent invoice as PDF.",
        "Open my GCP billing console and download the last 6 invoice PDFs into ~/Documents/gcp-invoices/.",
    ],
    # ---- Seed 19: example.com products scrape ----
    "scrape https://example.com/products and list every item with its current price": [
        "scrape example.com/products",
        "list all products + prices from example.com",
        "pull product prices from this site",
        "Scrape https://example.com/products and list every item with its current price.",
        "Pull every product from example.com/products and save name + price to CSV.",
        "Could you scrape https://shop.example.com and dump SKU + price + stock into a CSV?",
        "Scrape https://us.aritzia.com/en/category/tops and list every product with current price.",
        "Visit https://store.bambulab.com/products and pull SKU, name, price, and in-stock status into a CSV.",
        "Scrape https://example.com/products, follow each product link to get the full description, and save title, price, description, image URL, and stock status to a CSV.",
        "Scrape https://news.ycombinator.com/jobs, follow each job link, and produce a structured CSV with company, role, comp band (if listed), location, and the date posted. Skip jobs older than 30 days.",
        "Scrape https://uplift.com and list every standing-desk model with its current price and dimensions.",
        "pull products + prices from https://example.com/products into a csv",
        "Could you scrape https://example.com/products and produce a JSON file with every item's name, price, currency, image URL, and product page URL? Use Playwright if needed — the site renders client-side.",
        "Open https://amazon.com/stores/eero and scrape the product listings into a CSV with price + reviews.",
        "Scrape https://store.minisforum.com/collections/all and list every mini-PC with price and CPU.",
        "Pull every job listing from https://greenhouse.io/openai into a CSV with role, team, and location.",
    ],
    # ---- Seed 20: flight check ----
    "check if my flight UA853 on united.com is delayed or on time today": [
        "is UA853 delayed?",
        "check flight UA853 status",
        "look up my flight on united.com",
        "Check if my flight UA853 on united.com is delayed or on time today.",
        "Look up flight DL422 on delta.com and tell me if it's on schedule.",
        "Could you check the status of AA1234 on aa.com — is it on time, delayed, or canceled?",
        "Visit united.com and tell me the gate and departure time for UA853 today.",
        "Open lufthansa.com and check the current status of LH404 to JFK.",
        "Look up flight UA853 on united.com today and report: current status, scheduled vs estimated departure, gate, and any inbound-aircraft delays I should know about.",
        "Check the status of my flight UA853 on united.com. Also check the inbound flight that becomes UA853 — if that inbound is delayed by more than 30 minutes, recommend whether I should rebook to UA856 instead.",
        "Check Amtrak Northeast Regional 175 for delays today.",
        "check ua853 status on united.com — delayed or on time?",
        "Could you check united.com to see if my flight tonight, UA853 from SFO to EWR, is currently showing as on time? My departure is 8:25 PM local. Pop the gate number too if it's been assigned.",
        "Visit jetblue.com and check the status of B6 1234 from BOS to LAX.",
        "Open ana.co.jp and check the status of NH7 from NRT to ORD today.",
        "Look up flight AS123 on alaskaair.com and tell me if it's delayed or canceled.",
    ],
    # ---- Seed 21: TODO comments report ----
    "open my repo, find all TODO comments, and write a summary report grouped by author": [
        "TODO report grouped by author",
        "find all TODOs in my repo",
        "audit TODO comments",
        "Open my repo, find all TODO comments, and write a summary report grouped by author.",
        "Audit my codebase for TODO/FIXME/HACK comments and group them by git blame author.",
        "Could you scan the repo for any TODO comments and produce a markdown report sorted by oldest?",
        "Find every FIXME in src/ and report the file:line + the surrounding context.",
        "Audit the codebase for `TODO`, `FIXME`, and `XXX` comments, group them by author via git blame, and produce a markdown report with one section per author.",
        "Open my repo, run a search across all source files for TODO/FIXME/HACK/XXX/NOTE comments, group them by the author who wrote them (via git blame), produce a markdown report with sections per author, file:line links, and surrounding context, and save the report to docs/tech-debt.md.",
        "Audit our monorepo for stale TODOs (older than 1 year by git blame), group by author, file an issue on GitHub for each, and assign to the author. Skip TODOs in vendor/ and node_modules/.",
        "Find every `unimplemented!()` and `todo!()` in my Rust workspace and report which crates and authors they live in.",
        "scan repo for TODO + FIXME comments, group by author via git blame, output as markdown",
        "Could you walk through my repo and find every TODO comment? I want a report grouped by the author (use git blame), with the file:line, the comment text, and how old the TODO is.",
        "Open my Python project, find every `# TODO:` and `# FIXME:` comment, and produce a JSON report with author, age, and file location.",
        "Audit my repo for any disabled tests (`@pytest.mark.skip`, `it.skip`, `xit`) and produce a report of which engineer disabled each.",
        "Scan the repo for all `console.log` calls left in production code and report them grouped by file.",
    ],
    # ---- Seed 22: streamlit weather ----
    "build a Streamlit app that fetches weather from openweathermap.org and plots a 7-day forecast": [
        "streamlit weather app",
        "build a weather forecast UI",
        "weather dashboard via streamlit",
        "Build a Streamlit app that fetches weather from openweathermap.org and plots a 7-day forecast.",
        "Author a Streamlit app that pulls 7-day forecasts from OpenWeatherMap and charts them.",
        "Could you build a Gradio app that fetches air-quality data from airnow.gov and shows it on a map?",
        "Build a small Dash app that pulls stock prices from yfinance and plots a candlestick chart.",
        "Spin up a Streamlit app that pulls live cryptocurrency prices from CoinGecko and plots a 24-hour chart.",
        "Build a Streamlit app that fetches the 7-day forecast for a user-entered ZIP code from openweathermap.org and plots temperature, precipitation, and wind on three separate charts.",
        "Build a Streamlit weather app that takes a city name, calls OpenWeatherMap's free 7-day forecast endpoint, and plots the daily high/low, precipitation probability, and wind speed on three side-by-side Plotly charts. Cache responses for 15 minutes to stay under the free-tier quota.",
        "Build a Streamlit app that fetches NWS alerts for a given US state and shows them on a Folium map.",
        "build streamlit app: fetch openweathermap 7-day forecast for a zip code + plot",
        "Could you put together a Streamlit dashboard that takes a zip code from the user, calls openweathermap.org, and plots the 7-day forecast (temp high/low, precip chance) as a Plotly chart?",
        "Build a Streamlit app that pulls live transit times from the MBTA API and shows the next train for a chosen station.",
        "Author a Streamlit app that fetches surf forecasts from surfline.com and ranks the next 5 days for a given break.",
        "Build a Streamlit app that pulls AQI data from purpleair.com near a given GPS coordinate and plots a 24-hour history.",
    ],
    # ---- Seed 23: S3 -> BigQuery pipeline ----
    "refactor my data pipeline to read from S3 and write to BigQuery using batch loads": [
        "s3 -> bigquery pipeline",
        "refactor pipeline: s3 reads, bq batch writes",
        "migrate pipeline to s3 + bigquery",
        "Refactor my data pipeline to read from S3 and write to BigQuery using batch loads.",
        "Restructure my ETL to source from S3 parquet files and load into BigQuery via batch jobs.",
        "Could you refactor my Airflow DAGs so they read from GCS and write to Snowflake instead of S3 -> Redshift?",
        "Migrate my dbt project from Redshift to BigQuery, updating macros and incremental strategies.",
        "Rework my Glue ETL job to read parquet from S3 and write to BigQuery using the BQ Storage Write API.",
        "Refactor my data pipeline to read parquet from s3://mybucket/raw/, transform in DuckDB, and load into BigQuery using batch loads (not streaming inserts) every 15 minutes.",
        "Refactor my data pipeline so it: (1) reads daily parquet partitions from s3://mybucket/raw/dt=YYYY-MM-DD/, (2) deduplicates on primary key in DuckDB, (3) writes the result to GCS, (4) triggers a BigQuery load job that uses MERGE into the destination table. Idempotent on rerun.",
        "Refactor my Spark pipeline to read from S3, transform with PySpark, and write to BigQuery using the Spark BigQuery connector with indirect writes.",
        "refactor my etl: read s3 parquet, batch-load into bigquery",
        "Could you refactor my data pipeline? It currently reads from S3 and writes to Redshift. I want it to keep reading from S3 but write to BigQuery using batch loads. Switch to the BigQuery Storage Write API if it makes sense.",
        "Migrate my Airbyte connection from S3 -> Postgres to S3 -> BigQuery.",
        "Refactor my Dagster assets so they materialize from S3 parquet into BigQuery, with proper partition definitions.",
        "Move my Prefect flow from S3 -> Redshift to S3 -> BigQuery batch loads.",
    ],
    # ---- Seed 24: GitHub Action pytest + coverage ----
    "create a GitHub Action that runs pytest on every PR and comments coverage deltas": [
        "github action: pytest + coverage on PRs",
        "ci that posts coverage delta",
        "set up pytest + coverage CI",
        "Create a GitHub Action that runs pytest on every PR and comments coverage deltas.",
        "Set up CI to run pytest on every pull request and post the coverage diff as a comment.",
        "Could you create a CircleCI config that runs jest on every PR and reports coverage to Codecov?",
        "Add a GitHub Actions workflow that runs cargo test and posts a comment with timing differences vs main.",
        "Configure a GitLab CI pipeline to run pytest with coverage and gate the merge on >85% line coverage.",
        "Create a GitHub Action that runs pytest + coverage on every PR, posts the line-coverage delta vs main as a sticky PR comment, and fails the check if total coverage drops by more than 1 percentage point.",
        "Author a GitHub Actions workflow that, on every pull request, runs pytest with --cov, compares the coverage report to main's last known coverage, posts a sticky comment with the delta and any newly-uncovered lines, and gates the check on coverage not dropping by more than 1 pp. Run on Python 3.10/3.11/3.12 matrix.",
        "Add a GitHub Action that runs golangci-lint and `go test ./...` on every PR and comments any new lint warnings.",
        "set up gh actions: pytest + coverage comment on prs, fail on cov drop >1pp",
        "Could you set up GitHub Actions to run pytest on every pull request and comment the coverage delta versus main? Bonus if it also posts the list of files that lost coverage.",
        "Create a GitHub Action that runs `bun test --coverage` on every PR and surfaces the coverage delta.",
        "Add a GitHub Action that runs my Playwright suite on every PR and uploads videos of any failed tests as artifacts.",
        "Set up CI to run my Rust test suite with cargo-llvm-cov and comment coverage diffs on every PR.",
    ],
    # ---- Seed 25: prod 500s on /checkout ----
    "investigate why the prod API returns 500s on /checkout and fix the root cause": [
        "debug prod /checkout 500s",
        "find + fix the checkout 500 errors",
        "root-cause the checkout failures",
        "Investigate why the prod API returns 500s on /checkout and fix the root cause.",
        "Find and fix the bug behind the 500-error spike on /checkout in production.",
        "Could you root-cause and patch the 500s we're seeing on the /login endpoint in prod?",
        "Investigate the 502s on api.example.com/cart and identify whether it's the gateway, the app, or upstream.",
        "Debug the production database connection pool exhaustion that's causing /checkout to time out.",
        "Investigate the 500-error rate on /checkout. Pull the last hour of logs from Datadog, identify the most common stack trace, find the root cause in the code, fix it, and write a regression test that would've caught it.",
        "Investigate why our /checkout endpoint started returning 500s at 14:00 UTC today. Cross-reference the deploy timeline, look at error traces in Sentry, identify the regression, write a regression test, apply the minimum-diff fix, and roll forward. Don't roll back unless the fix would take more than 30 minutes.",
        "Find and fix the bug causing /api/v2/payments to time out after 30 seconds for ~5% of requests.",
        "investigate prod /checkout 500s + ship a fix w/ regression test",
        "Could you dig into why our /checkout endpoint is returning 500s in production? Sentry says it started about 90 minutes ago and correlates with a deploy. Root-cause it, fix it, and add a test so we don't regress.",
        "Debug the OOM kills on our payments service pod since yesterday's release and patch the root cause.",
        "Investigate why /api/orders is returning 504s when called from the mobile app but not the web app, and fix it.",
        "Root-cause the intermittent 500 on /api/users/:id endpoint and patch it.",
    ],
    # ---- Seed 26: CPU monitor + webhook ----
    "write a script that monitors my CPU usage every minute and alerts via webhook over 80%": [
        "cpu watchdog script",
        "monitor cpu + alert via webhook",
        "alert me when cpu > 80%",
        "Write a script that monitors my CPU usage every minute and alerts via webhook over 80%.",
        "Author a small daemon that samples CPU every 60 seconds and posts to a Slack webhook above 80%.",
        "Could you write a Bash script that watches disk usage every 5 minutes and alerts via PagerDuty over 90%?",
        "Write a script that tails /var/log/syslog and POSTs to a Slack webhook on any 'ERROR' line.",
        "Author a Python service that watches memory usage and emits an OpenTelemetry metric every 30 seconds.",
        "Write a script that samples CPU every minute via psutil, computes a 5-minute rolling average, and POSTs to a Slack webhook whenever it exceeds 80%. Suppress duplicate alerts within a 15-minute window.",
        "Author a small Go binary that monitors host CPU, memory, and disk every minute, computes 1-minute and 5-minute rolling averages for each, and POSTs to a configurable webhook URL whenever any of them crosses configurable thresholds (defaults 80/85/90). Suppress duplicate alerts within a configurable window.",
        "Write a script that monitors GPU utilization on my training rig and alerts via Discord webhook when utilization drops below 50% for more than 10 minutes (model probably crashed).",
        "write a script: poll cpu every 60s, POST to webhook if >80% for 3 consecutive samples",
        "Could you write me a small Python service that watches CPU usage and sends a Slack webhook ping whenever it goes above 80%? Sample every minute, debounce 15 min between alerts.",
        "Write a Bash script that runs every minute via cron and POSTs to a webhook if `uptime` reports load average above 2.0.",
        "Author a systemd-watched daemon in Rust that monitors CPU, memory, and disk and emits webhook alerts on threshold crossings.",
        "Write a Python script that monitors the number of zombie processes on a host and alerts via webhook when it exceeds 10.",
    ],
    # ---- Seed 27: cron backup ----
    "set up a cron job that backs up my notes folder to S3 nightly with versioning": [
        "nightly notes backup to s3",
        "cron: backup notes to s3 every night",
        "automate my notes folder backup",
        "Set up a cron job that backs up my notes folder to S3 nightly with versioning.",
        "Configure a nightly cron job that uploads ~/notes to s3://my-backups/notes/ with versioning.",
        "Could you set up a cron that rsyncs my photos to a B2 bucket every Sunday?",
        "Add a systemd timer that backs up my Postgres database to GCS every night.",
        "Set up a cron job on my homelab that snapshots my Docker volumes to a NAS daily and prunes snapshots older than 30 days.",
        "Set up a cron job that runs at 2 AM nightly, tars up ~/notes/, gzips it, uploads the archive to s3://mybackups/notes/$(date +%Y-%m-%d).tar.gz, and verifies the upload before deleting the local tar.",
        "Set up a cron job that nightly backs up my ~/notes directory. Use restic with an S3 backend, snapshot the directory, prune the snapshots to keep daily/weekly/monthly retention (7/4/12), and post the result to a healthcheck.io ping URL.",
        "Schedule a borg-backup of /home to a Hetzner Storage Box every night at 03:00 with 14-day retention.",
        "set up nightly cron: tar+gzip ~/notes -> s3 w/ object versioning + 30-day retention",
        "Could you set up a nightly cron job that tarballs my Obsidian vault, uploads it to S3 with versioning enabled, and pings a Healthchecks.io URL on success? Also email me if it fails three nights in a row.",
        "Set up a cron that backs up my MariaDB databases nightly to Backblaze B2 with 90-day retention.",
        "Add a launchd job on macOS that backs up ~/Documents to S3 every night.",
        "Schedule a daily rclone sync of my Google Drive to a local NAS, with versioning for the last 30 days.",
    ],
    # ---- Seed 28: CRA -> Vite port ----
    "port my React app from Create React App to Vite without breaking the build": [
        "cra -> vite",
        "migrate cra to vite",
        "port my react app to vite",
        "Port my React app from Create React App to Vite without breaking the build.",
        "Migrate my Create-React-App project to Vite, keeping all routes and env vars working.",
        "Could you migrate my Next.js Pages router app to the App router?",
        "Port my Vue 2 + webpack project to Vue 3 + Vite, updating all imports.",
        "Migrate my CRA app to Vite, swap react-scripts for vite, port the env-var prefix from REACT_APP_ to VITE_, and update all the corresponding usages.",
        "Migrate my CRA React app to Vite. Steps: swap react-scripts for vite + @vitejs/plugin-react; convert REACT_APP_* env vars to VITE_*; update CI scripts; replace any process.env references in client code; ensure Jest is replaced with Vitest or kept; verify all routes still build.",
        "Migrate my Create React App project to Vite. The app is in TypeScript, uses MUI, react-router v6, and Redux Toolkit. CI runs jest. I need: vite config equivalent to the CRA defaults including absolute imports from src/, ENV var rename from REACT_APP_ to VITE_, jest -> vitest migration, and the build output landing in the same /dist directory the deploy expects.",
        "Migrate my Create React App project to Next.js 14 App Router, preserving routes.",
        "port my CRA app to vite — keep all routes + env vars working, swap jest for vitest",
        "Could you migrate my CRA app to Vite? It's a fairly standard TS+MUI+react-router-v6 setup. The build script is the main thing I need to keep working; CI runs `npm run build` and uploads /build.",
        "Port my Gatsby site to Astro, preserving the existing content collections.",
        "Migrate my React app from webpack 4 to Vite, including the SVG-as-component loaders.",
        "Port my Snowpack-based React app to Vite without breaking dev tooling.",
    ],
    # ---- Seed 29: OAuth2 to Express ----
    "add OAuth2 login to my Express server using passport and the Google strategy": [
        "add google oauth2 to express",
        "passport-google for my express app",
        "set up google sign-in in express",
        "Add OAuth2 login to my Express server using passport and the Google strategy.",
        "Wire up Sign-in-with-Google to my Express app using passport-google-oauth20.",
        "Could you add GitHub OAuth login to my Flask app using authlib?",
        "Add Sign-in-with-Apple to my Express + React app.",
        "Add OIDC login to my FastAPI service against Auth0 using authlib's OAuth client.",
        "Add OAuth2 login to my Express server using passport-google-oauth20. Persist users in Postgres via prisma, set an httpOnly session cookie, and expose /auth/google/login and /auth/google/callback routes.",
        "Add full OAuth2 login to my Express server. Use passport with the Google strategy. After successful auth, upsert the user into Postgres, set a secure session cookie (httpOnly, Secure, SameSite=Lax), and redirect to /dashboard. Include CSRF protection on the callback and a unit test for the success and failure paths.",
        "Add Sign-in-with-Microsoft to my Express app using passport-azure-ad.",
        "add oauth2 (google strategy) to my express app via passport, persist users to pg",
        "Could you add Google OAuth2 login to my Express server? I want passport-google-oauth20, session cookies, and a redirect to /dashboard after success. Users live in a Prisma-managed Postgres table.",
        "Add OAuth2 device-flow login to my CLI written in Go.",
        "Wire up Sign-in-with-Discord on my SvelteKit app using lucia-auth.",
        "Add OAuth2 SSO to my admin dashboard using passport-saml against Okta.",
    ],
    # ---- Seed 30: notebook to module + CLI ----
    "convert my Jupyter notebook to a reusable Python module with a proper CLI entry point": [
        "notebook -> python module",
        "ipynb to cli",
        "convert my notebook to a real python package",
        "Convert my Jupyter notebook to a reusable Python module with a proper CLI entry point.",
        "Extract the logic from my .ipynb into a Python package and add a console_scripts CLI entry.",
        "Could you convert my Colab notebook into a Click-based CLI?",
        "Turn my exploration notebook into a typed Python module with argparse and a pyproject entry_points block.",
        "Convert my data-cleaning notebook to a CLI tool: argparse, logging, idempotent over its outputs, with a -q quiet flag.",
        "Convert my Jupyter notebook (`analysis.ipynb`) into a proper Python module: extract reusable functions into src/myapp/, write a CLI with argparse that exposes the main entrypoint, add type hints throughout, and write a smoke test that exercises the CLI on a sample input.",
        "Take my analysis.ipynb, extract every cell that mutates state into a typed function, group related functions into modules under src/myapp/, write a Typer-based CLI that wraps the top-level analysis pipeline, add a pyproject.toml with `myapp = myapp.cli:app` in [project.scripts], and remove the original notebook from the repo or move it to docs/.",
        "Convert my Observable notebook to a TypeScript module that I can import into a regular Node project.",
        "convert my ipynb into a python module + click cli, drop the notebook after",
        "Could you take my Jupyter notebook and turn it into a reusable Python module? I want a clean src/ layout, argparse CLI, type hints throughout, and the original notebook either deleted or moved to a docs/ folder.",
        "Refactor my Marimo notebook into a Python package with a CLI entry point.",
        "Convert my R Markdown notebook to an R package with a Roxygen-documented public API.",
        "Take my analysis.ipynb and split it into reusable Python functions + a Streamlit UI that wraps them.",
    ],
}


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for seed, variations in SEED_VARIATIONS.items():
        for text in variations:
            rows.append({
                "text": text,
                "label": "agentic",
                "source": "synthesized",
                "dataset": "llm-expansion",
            })
    with OUTPUT.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=["text", "label", "source", "dataset"])
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {len(rows)} rows to {OUTPUT}")


if __name__ == "__main__":
    main()
